spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: supermirkoplus@gmail.com
    password: testdevelhope
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
